package cloud.autotests.tests;

import io.qameta.allure.Description;
import org.junit.jupiter.api.*;

import static cloud.autotests.helpers.DriverHelper.getConsoleLogs;
import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class AppTests extends TestBase {
    @Test
    @Description("Soon to be implemented by QA.GURU engineers")
    @DisplayName("The fastest path should be displayed first")
    void generatedTest() {
        step("Open \"https://qa-metro.stand-1.praktikum-services.ru\"", () -> {
            // todo
        });

        step("Select city \"Москва\"", () -> {
            // todo
        });

        step("Type to field From \"Пятницкое шоссе\"", () -> {
            // todo
        });

        step("Type to field To \"Шипиловская\"", () -> {
            // todo
        });

        step("Verify that the fastest path display first", () -> {
            // todo
        });
    }

    @Test
    @Description("Autogenerated, because test steps contain text 'http...' and the page has 'title' tag")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://qa-metro.stand-1.praktikum-services.ru'", () ->
            open("https://qa-metro.stand-1.praktikum-services.ru"));

        step("Page title should have text 'Схема метро Москвы — Яндекс.Метро'", () -> {
            String expectedTitle = "Схема метро Москвы — Яндекс.Метро";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated, because test steps contain text 'http...'")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://qa-metro.stand-1.praktikum-services.ru'", () ->
            open("https://qa-metro.stand-1.praktikum-services.ru"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}